name: 'release'

on:
  push:
    tags: [ '*' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        id: install-dependencies
        run: make composer

      - name: PHPCS checker
        id: php-codesniffer
        run: make lint

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#fetch-jft'
        if: failure()

  package:
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: "build"
      DIST_DIR_GITHUB: "dist/github"
      GITHUB_RELEASE_FILENAME: "fetch-jft-plugin.zip"
      PLUGIN: "fetch-jft"
      MAINFILE: "fetch-jft-plugin.php"
    needs: [ lint ]
    steps:
      - uses: actions/checkout@v2
        id: code-checkout

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        id: install-dependencies
        uses: php-actions/composer@v5
        with:
          php_version: 7.4
          args: --prefer-dist --no-progress --no-suggest

      - name: Build package
        id: build-package
        run: |
          export ZIP_FILENAME=fetch-jft-plugin-build${GITHUB_RUN_NUMBER}-${GITHUB_SHA}.zip
          find ./ -type d | xargs chmod 755
          find ./ -name '*.php' | xargs chmod 644
          echo ${GITHUB_SHA} > build.txt
          zip -r $ZIP_FILENAME ./ -x "*.git*" -x "*.editorconfig*" -x "*.phpcs.xml" -x "*vendor*" -x "Dockerfile" -x "docker-compose*" -x "*assets*" -x "composer.*" -x "*docs*"
          mkdir $BUILD_DIR && cp $ZIP_FILENAME $BUILD_DIR/
          mv $ZIP_FILENAME fetch-jft-${GITHUB_REF##*/}.zip
          mkdir -p $DIST_DIR_GITHUB && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME
          curl -LO https://raw.githubusercontent.com/bmlt-enabled/release-notes-tool/master/gh-release-notes.sh
          chmod +x gh-release-notes.sh
          ./gh-release-notes.sh readme.txt "wp"
          curl -LO https://raw.githubusercontent.com/bmlt-enabled/bmlt-wordpress-deploy/master/deploy-wordpress.sh
          chmod +x deploy-wordpress.sh

      - name: Prepare artifact metadata
        id: prepare_artifact_metadata
        run: |
          echo ::set-output name=ARTIFACT_PATH::./fetch-jft-${GITHUB_REF##*/}.zip
          echo ::set-output name=ARTIFACT_NAME::fetch-jft-${GITHUB_REF##*/}.zip

      - name: Release beta
        if: contains(github.ref, 'beta')
        id: beta_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          prerelease: true
          draft: false

      - name: Upload Beta Asset
        if: contains(github.ref, 'beta')
        id: beta-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.beta_release.outputs.upload_url }}
          asset_path: ${{ steps.prepare_artifact_metadata.outputs.ARTIFACT_PATH }}
          asset_name: ${{ steps.prepare_artifact_metadata.outputs.ARTIFACT_NAME }}
          asset_content_type: application/zip

      - name: Release stable
        if: "!contains(github.ref, 'beta')"
        id: stable_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: "changelog.txt"
          prerelease: false
          draft: false

      - name: Upload Stable Asset
        if: "!contains(github.ref, 'beta')"
        id: stable-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.stable_release.outputs.upload_url }}
          asset_path: ${{ steps.prepare_artifact_metadata.outputs.ARTIFACT_PATH }}
          asset_name: ${{ steps.prepare_artifact_metadata.outputs.ARTIFACT_NAME }}
          asset_content_type: application/zip

      - name: Wordpress Release
        if: "!contains(github.ref, 'beta')"
        id: wordpress-stable-release
        env:
          WORDPRESS_USERNAME : ${{ secrets.WORDPRESS_USERNAME }}
          WORDPRESS_PASSWORD : ${{ secrets.WORDPRESS_PASSWORD }}
        run: |
          ./deploy-wordpress.sh
